### ISSUE TITLE
Toggle attributes with setAttr

### ISSUE THREAD

**Issue by h2so5** [redom/redom#104]
It would be nice if I could add/remove attributes with ease.
Would you consider modifying `setAttr` to handle a boolean value like Mithril?

```js
setAttr(el, { checked: true })   // => <input type=checkbox checked>
setAttr(el, { checked: false })  // => <input type=checkbox>
```

**Comment by pakastin** [comment]
That's how it works already, because it autodetects properties 😉

However *because* it's using properties in that case, it doesn't render it to the HTML—yet it's still checked:
https://codepen.io/pakastin/pen/PQaRRK

**Comment by pakastin** [comment]
I mean if you read the `el.checked` value it's `true`, but `el.getAttribute('checked')` is not. There's a difference between properties and attributes. It's the same thing with `value` for example..

**Comment by h2so5** [comment]
@pakastin Thanks for the quick response!
Sorry, my example was wrong... Indeed, the property access is enough for `checked`.
But I also want to toggle custom data attributes such as `data-error`.

`setAttr` seem not to support setting `data-error` through `dataset` property: https://codepen.io/anon/pen/bLKKwd
```
Uncaught TypeError: Cannot assign to read only property 'dataset' of object '#<HTMLInputElement>'
```

And even if `addAttr` supports `dataset`, there is no way to remove attributes.

**Comment by pakastin** [comment]
I'll add support for `dataset` Object, just a moment..

**Comment by pakastin** [comment]
Done!

https://github.com/redom/redom/releases/tag/v3.11.1
https://codepen.io/anon/pen/bLKKwd

😉

**Comment by pakastin** [comment]
Thanks for letting know about the issue and hope you like RE:DOM! 😎👍

**Comment by h2so5** [comment]
@pakastin Thank you!
But my issue is not solved: How to remove `data-error`?
Once `data-error` has been set, `setAttr` could not remove it: https://codepen.io/anon/pen/VQdBya
```js
// Setting falsy value like `false`, `null`, `undefined` won't work.
setAttr(el, {
  dataset: {
    error: null
  }
})

// delete manually
delete el.dataset.error
```

**Comment by pakastin** [comment]
What if you set it to `null`? That’s usually the preferred way..

**Comment by h2so5** [comment]
Setting it to `null` results in `error-data="null"`.
Do you mean interpreting `error-data="null"` as if `error-data` attribute is not set?
It's not css-friendly. (I have to use a selector like `:not([data-error=null])`)

I googled and some articles claim that setting null to `dataset.error` will remove `data-error` attribute but could not confirm such behaviors in any browsers.

**Comment by pakastin** [comment]
Oh, ok – sorry, I haven’t used data attributes that much. I’ll fix that!

**Comment by pakastin** [comment]
Oh, ok – sorry, I haven’t used data attributes that much. I’ll fix that!

**Comment by czb** [comment]
Maybe I miss something but I think there is no way to say `delete something` in a declarative (JSON like) manner. The only correct way probably is `delete el.dataset.error`. If you decide to delete by assigning `undefined` or `null`, how do you assign `undefined` or `null` if you need to?

**Comment by pakastin** [comment]
`undefined` in JSON means it’s not even defined, so it’s not quite idiomatic. Mongoose at least uses `null` to delete, so that would make sense to use.

**Comment by maxxheth** [comment]
Hi everyone! I'm aware this is a closed (and rather old) issue, but after creating my middleware function to generate data attributes on the fly (and then figuring out how to actually add data attributes via this thread..lol), you could probably go about setting a "data-error" attribute dynamically this way, which I think should allow you to sidestep having to "delete" the data-error attribute altogether:

## Conditional data attribute function 

```
const setDataAttr = el => dataAttrProps => {

    const { datasetName, value, error } = dataAttrProps;

    if (!error) { // If there's no error, proceed as usual.

        el.dataset[datasetName] = value;
    
        return el;

    } else { // Return the element with "data-error="some error message"...

        el.dataset.error = error;
        
        return el;

    }
    
};
```

## Plugging it into a component


```
class ExampleComponent {

    constructor(datasetName, datasetValue) {

        this.el = el('select.panel-card__select', el => setDataAttr(el)({

            datasetName: datasetName || 'component-data',
            value: datasetValue || 'some data',
            error: someErrorHandler() // Of course, this is contrived...

        }));

    }

}
```
I figured I'd just throw this out there for anyone else who stumbles onto this thread at random and would like to know how to dynamically insert data attributes into components on the fly. Loving RE:DOM so far @pakastin! =)
